apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kudabu.fullname" . }}-backend
  labels:
    {{- include "kudabu.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "kudabu.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        {{- include "kudabu.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.backend.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /api/config
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /api/config
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
