apiVersion: v1
kind: Service
metadata:
  name: {{ include "kudabu.fullname" . }}-backend
  labels:
    {{- include "kudabu.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.backendPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kudabu.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
